name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn install

    - name: Run TypeScript compiler
      run: yarn tsc
      continue-on-error: false

    - name: Set VITE_VERSION environment variable
      run: echo "VITE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build project
      run: yarn build
      env:
        VITE_FB_API_KEY: ${{ secrets.VITE_FB_API_KEY }}
        VITE_FB_AUTH_DOMAIN: ${{ secrets.VITE_FB_AUTH_DOMAIN }}
        VITE_FB_PROJECT_ID: ${{ secrets.VITE_FB_PROJECT_ID }}
        VITE_FB_STORAGE_BUCKET: ${{ secrets.VITE_FB_STORAGE_BUCKET }}
        VITE_FB_MESSAGING_SENDER_ID: ${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}
        VITE_FB_APP_ID: ${{ secrets.VITE_FB_APP_ID }}
        VITE_VERSION: ${{ env.VITE_VERSION }}

    - name: Deploy project
      run: yarn deploy
      env:
        VITE_FB_API_KEY: ${{ secrets.VITE_FB_API_KEY }}
        VITE_FB_AUTH_DOMAIN: ${{ secrets.VITE_FB_AUTH_DOMAIN }}
        VITE_FB_PROJECT_ID: ${{ secrets.VITE_FB_PROJECT_ID }}
        VITE_FB_STORAGE_BUCKET: ${{ secrets.VITE_FB_STORAGE_BUCKET }}
        VITE_FB_MESSAGING_SENDER_ID: ${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}
        VITE_FB_APP_ID: ${{ secrets.VITE_FB_APP_ID }}
        VITE_VERSION: ${{ env.VITE_VERSION }}
